environment:
    PACKAGE: "VimModelines"
    SUBLIME_TEXT_VERSION : "3"

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose

build: off

test_script:

    # run tests with test coverage report
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose

after_test:
    - "SET PYTHON=C:\\Python33"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install codecov
    - codecov